apiVersion: v1
kind: Service
metadata: 
  name: service-nodeport-web
spec:
  type: NodePort
  selector:
    app: web
  ports:        
  - protocol: TCP
    port: 8080        # Port d'ecoute à l'interieur du cluster
    targetPort: 8080  # Qui represente le port via lequel il va attaquer le endpoint , les ports qui sont derrières lui
    nodePort: 30008   # Le port à exposer à l'exterieur qui est celui qu'il faut atteindre pour acceder à l'application

