apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv
   labels:
    type: local
spec:
  storageClassName: manuel
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-pv"
