# le pv permet de centraliser les volumes contrairement aux volumes locaux
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv
   labels:
    type: local
spec:
  storageClassName: manuel
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-pv" # attention à ne pas creer le dossier par commande mkdir
