# le pvc permet de consommer une partie de pv qui vient dêtre créée
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc
   labels:
     type: local
spec:
  storageClassName: manuel   # ce nom doit avoir le même que pv et mode d'access doi être le même
  accessModes:
    - ReadWriteOnce
  resources: 
     requests:
       storage: 100Mi
           
